# Generated by Django 5.2.1 on 2025-05-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alumno',
            unique_together={('nombre', 'grupo')},
        ),
    ]
