# Generated by Django 5.2.1 on 2025-06-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alter_alumno_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='necesidad_medica',
            field=models.BooleanField(default=False),
        ),
    ]
