# Generated by Django 5.2.1 on 2025-05-27 07:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0002_alter_alumno_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialBathroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(default=django.utils.timezone.now)),
                ('tramo', models.PositiveSmallIntegerField(editable=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
            ],
        ),
    ]
