# Generated by Django 5.2.1 on 2025-05-28 18:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialbathroom',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
