# Generated by Django 5.2.1 on 2025-05-29 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0002_historialbathroom_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialbathroom',
            name='hora',
            field=models.TimeField(default=datetime.time(10, 37, 53, 226879)),
        ),
    ]
