# Generated by Django 5.2.1 on 2025-06-09 21:04

import applications.historial.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0003_alter_historialbathroom_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialbathroom',
            name='hora',
            field=models.TimeField(default=applications.historial.models.current_time_madrid),
        ),
    ]
