# Generated by Django 5.2.1 on 2025-05-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_user_per',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
