# Generated by Django 5.2.1 on 2025-05-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_type_user_per'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_user_per',
            field=models.CharField(max_length=100),
        ),
    ]
